export const GET_ALL_SOFTWARE_SUCCESS = 'GET_ALL_SOFTWARE_SUCCESS';
export const GET_ALL_SOFTWARE_REQUEST = 'GET_ALL_SOFTWARE_REQUEST';
export const GET_ALL_SOFTWARE_FAIL = 'GET_ALL_SOFTWARE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
